Fixes #9752: Document stopping process before Postgres restore maintenance to avoid primary key constrain get corrupted
Normation/rudder-doc pull request #1032
Opened 2024-04-16 12:18 UTC by ElaadF

https://issues.rudder.io/issues/9752

2024-04-16 12:20 UTC, amousset commented on src/reference/modules/installation/pages/upgrade/postgresql.adoc
> +Before perform any upgrade, make sure to *disable those services*, by disabling rudder agent *first* to be
```suggestion
Before performing any upgrade, make sure to *disable those services*, by disabling rudder agent *first* to be
```

2024-04-16 12:21 UTC, amousset commented on src/reference/modules/installation/pages/upgrade/postgresql.adoc
> +2. `systemctl stop rudder-relayd`
```suggestion
2. `systemctl stop rudder-relayd rudder-jetty`
```

2024-04-16 12:21 UTC, amousset commented on src/reference/modules/installation/pages/upgrade/postgresql.adoc
> +3. `systemctl stop rudder-jetty`
```suggestion
```

2024-04-16 12:24 UTC, ElaadF commented
Commit modified

2024-04-16 12:49 UTC, ncharles requested changes
Great content, i made some suggestion on wording

2024-04-16 12:49 UTC, ncharles commented on src/reference/modules/installation/pages/upgrade/postgresql.adoc
> +Before performing any upgrade, make sure to *disable those services*, by disabling rudder agent *first* to be
you need an empty line before here

2024-04-16 12:49 UTC, ncharles commented on src/reference/modules/installation/pages/upgrade/postgresql.adoc
> +Upgrading PostgreSQL without disabling these service can lead to inconsistencies and breaks some constraints on the database.
```suggestion
Upgrading PostgreSQL without disabling these service can lead to inconsistencies and might break constraints within the database schema.
```

2024-04-16 13:03 UTC, ElaadF commented
PR updated with a new commit

2024-04-16 13:04 UTC, ElaadF commented
PR rebased

2024-04-17 14:59 UTC, ncharles approved these changes

2024-04-17 15:00 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2024-04-17 15:00 UTC, merged