Fixes #18223: Add a page for technical stack doc
Normation/rudder-doc pull request #790
Opened 2020-09-18 14:18 UTC by amousset

https://issues.rudder.io/issues/18223

2020-09-18 15:23 UTC, fanf requested changes

2020-09-18 15:23 UTC, fanf commented on src/reference/modules/ROOT/pages/technical_stack.adoc
> +It is written in *https://www.rust-lang.org/[Rust]* (using the https://tokio.rs/[tokio] asynchronous runtime) to allow great performance even on very small hardware while providing to provide securit
providing to provide security

2020-09-18 15:23 UTC, fanf commented on src/reference/modules/ROOT/pages/technical_stack.adoc
> +* Stay as simple as possible, particularly on the operating side. Users should not have to spend
I think we need to add here somewhere: "this also means limiting the number of technologies in one given component"

2020-09-18 15:23 UTC, fanf commented on src/reference/modules/ROOT/pages/technical_stack.adoc
> +is mature and reliable, and also provides
missing end of sentence

2020-09-21 09:55 UTC, amousset commented
PR updated with a new commit

2020-09-21 09:58 UTC, fanf approved these changes

2020-09-21 09:58 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder-doc/pull/790`
-- Your faithful QA
Kant merge: "Live your life as though your every act were to become a universal law."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/30147/console)

2020-09-21 10:03 UTC, amousset commented
OK, squash merging this PR

2020-09-21 10:03 UTC, merged