Fixes #18350: Document Health Check in user doc
Normation/rudder-doc pull request #794
Opened 2020-10-26 14:48 UTC by ElaadF

https://issues.rudder.io/issues/18350

2020-10-26 15:18 UTC, amousset commented on src/reference/modules/administration/pages/server.adoc
> +To ensure the health of RUDDER, some checks are executed every 5 minutes by default. To change the period
```suggestion
To ensure the health of Rudder, some checks are executed every 5 minutes by default. To change the period
```

2020-10-26 15:19 UTC, amousset commented on src/reference/modules/administration/pages/server.adoc
> +To ensure the health of RUDDER, some checks are executed every 5 minutes by default. To change the period
Let's try to be locally consistent for now, we'll get back on the global level at some point

2020-10-26 15:23 UTC, amousset commented on src/reference/modules/administration/pages/server.adoc
> +you can change it to "30 seconds". Every check will return a message with a `Severity Level`
return how?

2020-10-26 15:36 UTC, ElaadF commented
Commit modified

2020-10-26 15:37 UTC, ElaadF commented
Commit modified

2020-10-26 15:42 UTC, amousset requested changes

2020-10-26 15:42 UTC, amousset commented on src/reference/modules/administration/pages/server.adoc
> +A notification will be displayed if at least one *Warning* or *Critical* has been returned by a Health Check run.
```suggestion
A notification will be displayed if at least one *Warning* or *Critical* has been returned by latest Health Check run.
```

2020-10-26 15:42 UTC, amousset commented on src/reference/modules/administration/pages/server.adoc
> +A notification will be displayed if at least one *Warning* or *Critical* has been returned by a Health Check run.
If I have understood correctly

2020-10-26 15:54 UTC, ElaadF commented
Commit modified

2020-10-26 15:55 UTC, amousset approved these changes

2020-10-27 09:18 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2020-10-27 09:18 UTC, merged