Fixes #20228: Document only ncf_const variables
Normation/rudder-doc pull request #863
Opened 2021-11-03 10:05 UTC by Fdall

https://issues.rudder.io/issues/20228

2021-11-05 14:20 UTC, Fdall commented
PR updated with a new commit

2021-11-23 20:21 UTC, ncharles requested changes
i don't see what would define these variables

2021-11-23 20:21 UTC, ncharles commented on src/reference/modules/usage/pages/variables.adoc
> +|`rudder_const.dollar`
i don't have such on variable on my rudder 6.2

2021-11-23 20:22 UTC, ncharles commented
related https://github.com/Normation/ncf/pull/1322/files

2021-11-23 20:22 UTC, ncharles requested changes
It should states that these variables appears in 6.2.11 (or better, in 7.0) otherwise people with older version of rudder will have a broken config

2022-12-09 10:51 UTC, VinceMacBuche approved these changes

2022-12-09 16:04 UTC, closed without merging