Fixes #21952: Documentation for FQDN overriding
Normation/rudder-doc pull request #930
Opened 2022-10-13 11:08 UTC by fanf

https://issues.rudder.io/issues/21952

2022-10-13 11:23 UTC, ElaadF requested changes

2022-10-13 11:23 UTC, ElaadF commented on src/reference/modules/usage/pages/advanced_node_management.adoc
> +If that key is defined, it is prefered to other values retrieved in agent inventory (`<RUDDER><HOSTNAME>` or else
preferred

2022-10-13 11:23 UTC, ElaadF commented on src/reference/modules/usage/pages/advanced_node_management.adoc
> +see on Rudder with the FQDN `"node1-overridden.rudder.local.override`:
remove the extra "

2022-10-19 14:00 UTC, ncharles commented
it misses the version in which the feature appeared in Rudder

2022-10-19 14:05 UTC, ElaadF commented
> it misses the version in which the feature appeared in Rudder

Can you open a ticket ?
This PR is obsolete, I will close it, the real one is here: https://github.com/Normation/rudder-doc/pull/931

2022-10-19 14:05 UTC, closed without merging