Fixes #21877: Hardening guide for Rudder
Normation/rudder-doc pull request #952
Opened 2023-02-16 09:24 UTC by amousset

https://issues.rudder.io/issues/21877

2023-02-16 10:34 UTC, amousset commented
PR updated with a new commit

2023-02-16 10:39 UTC, amousset commented
PR updated with a new commit

2023-02-16 10:45 UTC, amousset commented
PR updated with a new commit

2023-02-16 10:47 UTC, amousset commented
PR updated with a new commit

2023-02-16 10:57 UTC, amousset commented
PR updated with a new commit

2023-02-23 13:31 UTC, ncharles commented on src/reference/modules/administration/pages/security.adoc
> +* By default, all HTTPS traffic is handled by the same virtual host in Apache httpd. To allow hardening the connection security, a first step is to split public Web/API from internal node-server comm
You only need a way to make a difference in the configuration, in general with a different port (which allows applying different firewall rules too) or a specific domain for Web/API.
->
You need to define a method to distinguish both configurations, in general with a different port (which allows applying different firewall rules too) or a specific domain for Web/API.

2023-02-23 13:33 UTC, ncharles commented on src/reference/modules/administration/pages/security.adoc
> +* You may want to hide the Apache httpd version from the headers. It cannot be done inside Rudder's configuration as it is a global parameter. To do so, you need to set the `ServerTokens` parameter t
it is a global parameter. ->  it is a global Apache2 parameter.

2023-02-23 13:47 UTC, ncharles commented on src/reference/modules/administration/pages/security.adoc
> +This way, once the node sends its first inventory, if it matched the node id and certificate, it will be automatically accepted. Note that this creation call also allows pre-setting node properties.
this is misleading - the node is already existing within Rudder

This way, once the node sends its first inventory, if the node id and certificate match the pre-provisionned entry, the node inventory will be update.
Please note that you can also pre-defined node properties using this API, to ensure that the pre-provisionned node is already in the correct groups

2023-02-23 13:48 UTC, ncharles requested changes
This is a really neat document
Some minor changes on wording are requested to make it more understandable

2023-02-24 08:24 UTC, amousset commented
PR updated with a new commit

2023-02-24 08:25 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2023-02-24 08:25 UTC, merged